import ErosClient from "../../models/discord/ErosClient";
import Command from "../../models/command/Command.class";
import { Message, MessageEmbed } from "discord.js";
import { erosRed } from "../../colors";

class invite extends Command {

    constructor(client: ErosClient) {
        super(client, {
            name: 'invite', 
            aliases: ['botinvite', 'botinv', 'inv'], 
            description: 'Generates an invite for the bot', 
            category: 'information', 
            usage: 'invite'
        });
    }

    async run(message: Message, args: string[]) {
        const url: string = await this.client.generateInvite("ADMINISTRATOR");
        
        const embed: MessageEmbed = new MessageEmbed()
            .setColor(erosRed)
            .setTimestamp()
            .setFooter(`Generated by ${message.author.tag}`, message.author.displayAvatarURL())
            .setImage(this.client.user.displayAvatarURL({ dynamic: true }))
            .setTitle(`${this.client.user.username} invite link`)
            .setURL(url)
            .setDescription(`To invite me to _your_ server, either press the title above\nOr you can click [me](${url})`);

        message.channel.send(embed);
    }
}

export = invite;